version: '3'

services:
  pgdb:
    image: postgres:14
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: admin
      PGDATA: C:\Program Files\PostgreSQL\14\data